iPhone Product Landing Page
Orzala-2024/Product-Landing-Page1 pull request #1
Opened 2024-05-29 11:47 UTC by LimaSahibzada

🔘This is a product landing page which is designed for iPhone products . this repo contains below files:
* landing.html
* styles.css
* readme.md
* linters

2024-05-30 19:21 UTC, ahzamir requested changes
### Hi @LimaSahibzada 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Although your code passes the freecodecamp tests, but you still need to work on your project to get the final approval.
  - Check the below inline comments for more details

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
![image](https://github.com/LimaSahibzada/Product-Landing-Page1/assets/96838030/d4481596-5856-49bd-82c3-80c9681343a2)

✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed and completed the Product Landing Page and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your project has a professional README.md file
❌Your project code is clean

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-30 19:21 UTC, ahzamir commented on landing.html
- Your code spacing and alignment are not clean please have a look at your opening tag and closing tags and parent element and child elements for their alignment and spacing.

**Incorrect:**
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>
<h1>This is a Heading</h1>
        <p>This is a paragraph.</p>
    </body>
</html>
```

**Correct:**
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Page Title</title>
  </head>
  <body>
    <h1>This is a Heading</h1>
    <p>This is a paragraph.</p>
  </body>
</html>
```

**Rule:** Each child element should be indented 2 spaces under its parent element for better readability and maintainability.
**Hint**: Go to the VSCode bottom right corner, you can see "Spaces: 4" (or a similar indicator). Click on that, then click on "Indent Using Spaces" and select 2. You can also use the gray color column lines to help you know where your parent and child elements should be.

2024-05-30 19:21 UTC, ahzamir commented on landing.html
- [**OPTIONAL**] - You added a very great design to your project and it looks amazing, try to add some more page content and sections according to the navbar links you added so your product landing page looks better.

2024-05-30 19:21 UTC, ahzamir commented on README.md
> +![Technical Documentation page]![picof project](https://github.com/LimaSahibzada/Product-Landing-Page1/assets/167701815/542382ee-8da5-4f5a-9649-ef2cfd524cb1)
- Remove one of these `![Technical Documentation page]`, `![picof project]`.
  - Just keep one of them as alt text for your Demo.

2024-05-31 04:12 UTC, LimaSahibzada commented
@ahzamir ,
Kindly review my project.

2024-06-01 10:25 UTC, ahzamir requested changes
@LimaSahibzada 
- Although you cleaned your code a little bit still there are some issues you need to work on check the below comments for more details:

2024-06-01 10:25 UTC, ahzamir commented on landing.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
- These codes should be inside your `<head>` tag

2024-06-01 10:25 UTC, ahzamir commented on landing.html
> +<title>Iphone Product Landing Page</title>
- Add two space here as title is a child for head tag

2024-06-01 10:25 UTC, ahzamir commented on landing.html
> +    </header>
- I can not see the closing tag for you div here add it.

2024-06-01 10:25 UTC, ahzamir commented on landing.html
> +      <iframe id="video" src="https://www.youtube.com/embed/FT3ODSg1GFE?si=0ZlweiXR5__er_ZS" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-me
- Remove the 2 spaces as they are not a child of your h1

2024-06-01 10:25 UTC, ahzamir commented on landing.html
> +      <iframe id="video" src="https://www.youtube.com/embed/FT3ODSg1GFE?si=0ZlweiXR5__er_ZS" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-me
- Here you have 3 closing tags just for one `<iframe>` solve it.

2024-06-01 10:25 UTC, ahzamir commented on landing.html
> +    </footer>
- Your 2 divs do not have a closing tags add them

2024-06-02 04:56 UTC, LimaSahibzada commented
@ahzamir ,
Kindly review my work. I made some changes.

2024-06-02 12:36 UTC, ahzamir approved these changes
### Hi @LimaSahibzada 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![GreatJobThumbsUpGIF](https://github.com/ZuhRa-HashiMi/survey-form/assets/96838030/cc459d3f-5796-43f0-aba7-4ed0c35fa276)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Product Landing Page project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your project has a professional README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-03 12:17 UTC, merged